openapi: "3.0.0"
info:
  title: Feature
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /v1/web-features:
    post:
      summary: Consumes the specified web feature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - location
              properties:
                location:
                  $ref: "#/components/schemas/ObjectLocation"
       

      responses:
        '200':
          description: Repository downloaded
        '400':
          description: Bad Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '429':
          description: Rate Limit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '500':
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
                          
components:
  schemas:
    ObjectLocation:
      type: object
      properties:
        gcs:
          $ref: '#/components/schemas/GCSObjectLocation'
    GCSObjectLocation:
      type: object
      properties:
        bucket:
          type: string
        object:
          type: string
      required:
        - bucket
        - object
    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/BasicErrorModel'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string