openapi: "3.0.0"
info:
  title: Repo Downloader Service
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /v1/github.com/{owner}/{name}:
    parameters:
      - name: owner
        in: path
        description: GitHub owner/org
        required: true
        schema:
          type: string
      - name: name
        in: path
        description: GitHub repository name
        required: true
        schema:
          type: string
    post:
      summary: Downloads the specified github repository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - archive
              properties:
                archive:
                  $ref: '#/components/schemas/TarInput'
                  # oneOf:
                  #   - $ref: '#/components/schemas/TarInput'
                  #     required:
                  #       - type
                  # discriminator:
                  #   propertyName: type
                  #   mapping:
                  #     TAR: '#/components/schemas/TarInput'
                file_filters:
                  type: array
                  items:
                    $ref: '#/components/schemas/FileFilter'
      responses:
        '200':
          description: Repository downloaded
          content:
            application/json:
              schema:
                required:
                  - destination
                properties:
                  destination:
                    $ref: "#/components/schemas/UploadDestinationReport"
        '400':
          description: Bad Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '429':
          description: Rate Limit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '500':
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
                          
components:
  schemas:
    UploadDestinationReport:
      type: object
      properties:
        gcs:
          $ref: '#/components/schemas/GCSUploadReport'
    GCSUploadReport:
      type: object
      required:
        - bucket
        - repo_prefix
      properties:
        bucket:
          type: string
        repo_prefix:
          type: string
        filenames:
          type: array
          items:
            type: string
    FileFilter:
      type: object
      properties:
        prefix:
          type: string
        suffix:
          type: string
      minProperties: 1
    ArchiveTypes:
      type: string
      enum:
        - TAR
    TarInput:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ArchiveTypes'
        tar_strip_components:
          type: integer
          description: The --strip-components flag for tar
          minimum: 0
          maximum: 1
          default: 1
      required:
        - type
    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/BasicErrorModel'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string