openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /v1/features:
    get:
      summary: List features
      parameters:
        - $ref: "#/components/parameters/paginationTokenParam"
        - $ref: "#/components/parameters/paginationSizeParam"
        - in: query
          name: baseline_start_year
          schema:
            type: integer
            minimum: 2023
            maximum: 2023
          description: Start range (inclusive) for when features became part of baseline
        - in: query
          name: baseline_end_year
          schema:
            type: integer
            minimum: 2023
            maximum: 2023
          description: End range (inclusive) for when features became part of baseline
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeaturePage'
        '400':
          description: Bad Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'                
        '429':
          description: Rate Limit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
        '500':
          description: Internal Service Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicErrorModel'
components:
  parameters:
    paginationTokenParam:
      in: query
      name: page_token
      schema:
        type: string
      description: Pagination token
      required: false
    paginationSizeParam:
      in: query
      name: page_size
      schema:
        type: integer
        maximum: 25
        minimum: 0
        default: 0
      required: false
      description: Number of results to return
  schemas:
    PageMetadata:
      type: object
      properties:
        next_page_token:
          type: string
    FeaturePage:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/PageMetadata'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
      required:
        - data
    Feature:
      type: object
      properties:
        feature_id:
          type: string
        spec:
          type: array
          items:
            type: string
      required:
        - feature_id
    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:     # Combines the BasicErrorModel and the inline model
        - $ref: '#/components/schemas/BasicErrorModel'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string